"""add_knowledge_base_tables

Revision ID: 61f7ee5bed9c
Revises: f18e19b1bcab
Create Date: 2026-06-01 11:13:06.186403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '61f7ee5bed9c'
down_revision: Union[str, None] = 'f18e19b1bcab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kb_id', sa.String(length=36), nullable=False, comment='Knowledge base ID'),
    sa.Column('doc_id', sa.String(length=36), nullable=False, comment='Document ID'),
    sa.Column('added_at', sa.DateTime(), nullable=True, comment='When document was added'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_documents_doc_id'), 'knowledge_base_documents', ['doc_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_documents_kb_id'), 'knowledge_base_documents', ['kb_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Knowledge base name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Knowledge base description'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Last update time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('conversation_records', 'document_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='Associated document ID',
               existing_comment='关联文档ID',
               existing_nullable=False)
    op.alter_column('conversation_records', 'conversation_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='Conversation session ID',
               existing_comment='对话会话ID',
               existing_nullable=False)
    op.alter_column('conversation_records', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='Role: user / assistant',
               existing_comment='角色: user / assistant',
               existing_nullable=False)
    op.alter_column('conversation_records', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Message content',
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('conversation_records', 'sources',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Source references (JSON)',
               existing_comment='引用来源 (JSON)',
               existing_nullable=True)
    op.alter_column('conversation_records', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='Creation time',
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('documents', 'filename',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Original filename',
               existing_comment='原始文件名',
               existing_nullable=False)
    op.alter_column('documents', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='File storage path',
               existing_comment='文件存储路径',
               existing_nullable=False)
    op.alter_column('documents', 'file_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='File extension',
               existing_comment='文件类型扩展名',
               existing_nullable=False)
    op.alter_column('documents', 'file_size',
               existing_type=mysql.INTEGER(),
               comment='File size in bytes',
               existing_comment='文件大小(字节)',
               existing_nullable=False)
    op.alter_column('documents', 'status',
               existing_type=mysql.ENUM('UPLOADED', 'PROCESSING', 'READY', 'FAILED', collation='utf8mb4_unicode_ci'),
               comment='Document processing status',
               existing_comment='文档处理状态',
               existing_nullable=False)
    op.alter_column('documents', 'chunk_count',
               existing_type=mysql.INTEGER(),
               comment='Number of text chunks',
               existing_comment='文本分块数量',
               existing_nullable=True)
    op.alter_column('documents', 'error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Error message',
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='Creation time',
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='Last update time',
               existing_comment='更新时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_comment='Last update time',
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_comment='Creation time',
               existing_nullable=True)
    op.alter_column('documents', 'error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='错误信息',
               existing_comment='Error message',
               existing_nullable=True)
    op.alter_column('documents', 'chunk_count',
               existing_type=mysql.INTEGER(),
               comment='文本分块数量',
               existing_comment='Number of text chunks',
               existing_nullable=True)
    op.alter_column('documents', 'status',
               existing_type=mysql.ENUM('UPLOADED', 'PROCESSING', 'READY', 'FAILED', collation='utf8mb4_unicode_ci'),
               comment='文档处理状态',
               existing_comment='Document processing status',
               existing_nullable=False)
    op.alter_column('documents', 'file_size',
               existing_type=mysql.INTEGER(),
               comment='文件大小(字节)',
               existing_comment='File size in bytes',
               existing_nullable=False)
    op.alter_column('documents', 'file_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='文件类型扩展名',
               existing_comment='File extension',
               existing_nullable=False)
    op.alter_column('documents', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='文件存储路径',
               existing_comment='File storage path',
               existing_nullable=False)
    op.alter_column('documents', 'filename',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='原始文件名',
               existing_comment='Original filename',
               existing_nullable=False)
    op.alter_column('conversation_records', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_comment='Creation time',
               existing_nullable=True)
    op.alter_column('conversation_records', 'sources',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='引用来源 (JSON)',
               existing_comment='Source references (JSON)',
               existing_nullable=True)
    op.alter_column('conversation_records', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='消息内容',
               existing_comment='Message content',
               existing_nullable=False)
    op.alter_column('conversation_records', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='角色: user / assistant',
               existing_comment='Role: user / assistant',
               existing_nullable=False)
    op.alter_column('conversation_records', 'conversation_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='对话会话ID',
               existing_comment='Conversation session ID',
               existing_nullable=False)
    op.alter_column('conversation_records', 'document_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='关联文档ID',
               existing_comment='Associated document ID',
               existing_nullable=False)
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_knowledge_base_documents_kb_id'), table_name='knowledge_base_documents')
    op.drop_index(op.f('ix_knowledge_base_documents_doc_id'), table_name='knowledge_base_documents')
    op.drop_table('knowledge_base_documents')
    # ### end Alembic commands ###
