"""add conversation_records table

Revision ID: f18e19b1bcab
Revises: 29ca326a7c91
Create Date: 2026-05-30 15:12:31.930672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18e19b1bcab'
down_revision: Union[str, None] = '29ca326a7c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='关联文档ID'),
    sa.Column('conversation_id', sa.String(length=36), nullable=False, comment='对话会话ID'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='角色: user / assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('sources', sa.Text(), nullable=True, comment='引用来源 (JSON)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_records_conversation_id'), 'conversation_records', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_records_document_id'), 'conversation_records', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_records_document_id'), table_name='conversation_records')
    op.drop_index(op.f('ix_conversation_records_conversation_id'), table_name='conversation_records')
    op.drop_table('conversation_records')
    # ### end Alembic commands ###
